In [1]:
import pandas as pd
df=pd.read_csv("earthquake_1995-2023.csv")
print("Rows and columns:",df.shape)
df.info()

Rows and columns: (1000, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [2]:
import pandas as pd
df=pd.read_csv("earthquake_1995-2023.csv")
dupe_mask=df.duplicated(subset=["title","date_time"],keep=False)
print("rows involved in a title+data_time duplicate:", dupe_mask.sum())
df[dupe_mask].sort_values("title")[["title", "date_time", "magnitude", "country"]]

rows involved in a title+data_time duplicate: 4

                                   title         date_time  magnitude country
67  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
68  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
70  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN
71  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN

In [3]:
import pandas as pd
df=pd.read_csv("earthquake_1995-2023.csv")
before = len(df)
df = df.drop_duplicates(subset=["title", "date_time"], keep="first").reset_index(drop=True)
after = len(df)
print(f"removed {before-after} duplicate row(s).")
print("Rows now:", after)

removed 2 duplicate row(s).
Rows now: 998

In [14]:
import pandas as pd
df=pd.read_csv("earthquake_1995-2023.csv")
missing = df['alert'].isnull().sum() # Calculate missing values for the 'alert' column
missing_report ={
    "missing_count": missing,
    "missing_percent": (missing/len(df)*100).round(2)
}

In [12]:
for col in ["cdi", "dmin", "gap", "nst"]:
  zeros =(df[col]==0).sum()
  print(f"{col:6s}: {zeros} zeros ({zeros / len(df):.2f})")

cdi   : 395 zeros (0.40)
dmin  : 586 zeros (0.59)
gap   : 252 zeros (0.25)
nst   : 519 zeros (0.52)

In [6]:
import numpy as np
for col in ["cdi", "gap"]:
  df[col]=df[col].replace(0,np.nan)
print("missing values now visible:")
print(df[["cdi", "gap"]].isnull().sum())

missing values now visible:
cdi    395
gap    252
dtype: int64

In [7]:
cdi_fill = df["cdi"].mean

In [8]:
import pandas as pd
df=pd.read_csv("earthquake_1995-2023.csv")
print("Rows and columns:",df.shape)
df.info()

Rows and columns: (1000, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [9]:
dupe_mask=df.duplicated(subset=["title","date_time"],keep=False)
print("Rows involed in a title+date_time duplicate:",dupe_mask.sum())
df[dupe_mask].sort_values("title")[["title","date_time","magnitude","country"]]

Rows involed in a title+date_time duplicate: 4

                                   title         date_time  magnitude country
67  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
68  M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39        6.5     NaN
70  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN
71  M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35        6.7     NaN

In [10]:
df.drop_duplicates(subset=["title","date_time"],inplace=True)

In [11]:
df.loc[66:71,["title","date_time"]]

                                    title         date_time
66  M 6.6 - 80 km SW of Labuan, Indonesia  14/01/2022 09:05
67   M 6.5 - 71 km SE of Nikolski, Alaska  11/01/2022 12:39
69   M 6.6 - 53 km SE of Nikolski, Alaska  11/01/2022 12:39
70   M 6.7 - 91 km SE of Nikolski, Alaska  11/01/2022 11:35